### ISSUE TITLE
❗ [버그][상세] FTP 파일 업로드 실패 오류

### ISSUE THREAD

**Issue by newjinlee** [Sejong-Balsamic/Malsami-BE#482]
🗒️ 설명
---
- 사진 업로드가 안됩니다 png 형식으로 올림
- ![image](https://github.com/user-attachments/assets/3b0ae7b1-f8e7-47cf-8a50-24f6e6258845)

```
2024-11-28T13:25:33.606+09:00 ERROR 1 --- [io-8080-exec-17] c.b.s.service.MediaFileService           : 파일 처리 중 오류 발생: FTP 파일 업로드에 실패했습니다.
2024-11-28T13:25:33.609+09:00  INFO 1 --- [io-8080-exec-17] c.b.s.u.log.ExecutionTimeLoggingAspect   : [saveQuestionPost] 실행시간: 45ms
2024-11-28T13:25:33.609+09:00  INFO 1 --- [io-8080-exec-17] c.b.s.u.l.MethodInvocationLoggingAspect  : [saveQuestionPost] RequestID: null, Result: INTERNAL_SERVER_ERROR
com.balsamic.sejongmalsami.util.exception.CustomException: FTP 파일 업로드에 실패했습니다.
        at com.balsamic.sejongmalsami.util.storage.FtpStorageService.uploadFile(FtpStorageService.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at com.balsamic.sejongmalsami.util.log.ExecutionTimeLoggingAspect.logMethod(ExecutionTimeLoggingAspect.java:24)
        at jdk.internal.reflect.GeneratedMethodAccessor241.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:173)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at com.balsamic.sejongmalsami.util.log.MethodInvocationLoggingAspect.logMethod(MethodInvocationLoggingAspect.java:39)
        at jdk.internal.reflect.GeneratedMethodAccessor242.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:173)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
```

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia 
- 프론트엔드: @newjinlee

**Comment by Cassiiopeia** [comment]
![image](https://github.com/user-attachments/assets/80407c5e-a985-4011-9afd-d72b4c7d20ca)




BROKEN PIPE 문제는 제대로된 원인을 파악하기 어려운데요....

예상하는 부분은

다음과 같습니다

서버쪽 FTP 세팅을 보아하니 300초 (5분) 으로 되어있는데 

코드적으로 타임아웃시간이 60초 로 걸려있어서 문제가 발생하는것으로 보입니다




![image](https://github.com/user-attachments/assets/00b035c2-fe5f-46e1-9361-6a6cefcb7d29)

![image](https://github.com/user-attachments/assets/2aacfce5-39b9-4050-88f3-aee959ef50ce)


그래서 

서버쪽 FTP 타임아웃시간인 5분과 맞게 코드를 수정하였습니다


혹시 몰라 안정장치들도 몇개 추가하였습니다

1. 재시도 로직 추가하였습니다

재시도 시 다음과 같게 표시되도록 변경될것같습니다
재시도 횟수는 최대 3번 실행하며 10초뒤에 재시도 합니다

```
INFO  - FTP 파일 업로드 시작: example.txt -> /path/to/example.txt
ERROR - FTP 파일 업로드 중 예외 발생 (시도 1): Broken pipe
WARN  - FTP 파일 업로드 재시도: 1번째 시도 실패. 1초 뒤에 다시 시도합니다...
ERROR - FTP 파일 업로드 중 예외 발생 (시도 2): Connection reset
WARN  - FTP 파일 업로드 재시도: 2번째 시도 실패. 1초 뒤에 다시 시도합니다...
INFO  - FTP 파일 업로드 성공: /path/to/example.txt
DEBUG - FTPClient 반환 완료: org.apache.commons.net.ftp.FTPClient@1a2b3c4
```

2. 연결 validate 로직에 대해서 연결상태만 확인하는것보다 연결이 유효한지도 확인하는 로직을 추가했습니다

![image](https://github.com/user-attachments/assets/32239427-aafe-46a5-be4a-5e33a38fc092)

![image](https://github.com/user-attachments/assets/cc452442-5030-4106-9d34-ced51118dc82)

해당 validateObject() 부분은

    poolConfig.setTestOnBorrow(true);
    poolConfig.setTestOnReturn(true);

코드의 해당 부분에서 자동으로 실행되어 체크합니다



## 결론

로깅 처리 잘 해놨다
재시도 로직 추가했다
문제의 원인인 것같은 TimeOut 초 시간을 서버랑 코드랑 동일하게 수정했다.

**Comment by Cassiiopeia** [comment]
근데 왜안될까요~? ^^

**Comment by Cassiiopeia** [comment]
업로드 로직 정상 작동 확인했습니다

@newjinlee  확인 부탁드립니다

문제점은 FTPClient 를 생성후에 연결후
소켓 타임아웃을 설정해야하는데

connect가 되지않았는데 소켓타임아웃을 설정하는바람에 
socket is null 이라는 오류가 떴었습니다 

![image](https://github.com/user-attachments/assets/320253f7-c2f1-4987-a18d-f13ec292ac01)
![image](https://github.com/user-attachments/assets/19840a34-425f-4220-92f8-4bf1654dbfbf)


해당 부분 수정하였습니다

다음과 같이 정상적으로 업로드되고 반환이됩니다
```
{
  "documentPost": {
    "createdDate": "2024-11-29T12:22:31.312952",
    "updatedDate": "2024-11-29T12:23:59.395858",
    "isEdited": true,
    "isDeleted": false,
    "isLiked": false,
    "dailyScore": 0,
    "weeklyScore": 0,
    "documentPostId": "a3b28ed5-50db-4d40-ad70-dd210b3093bd",
    "member": {
      "createdDate": "2024-11-23T12:16:08.491587",
      "updatedDate": "2024-11-29T12:17:02.081397",
      "isEdited": true,
      "isDeleted": false,
      "isLiked": false,
      "memberId": "1acdf07f-e104-465d-b26f-772153f6fc0d",
      "studentId": 18010561,
      "studentName": "서새찬",
      "uuidNickname": "b63d7b",
      "major": "바이오융합공학전공",
      "academicYear": "4",
      "enrollmentStatus": "졸업",
      "profileUrl": null,
      "isNotificationEnabled": true,
      "roles": [
        "ROLE_USER",
        "ROLE_ADMIN"
      ],
      "accountStatus": "ACTIVE",
      "lastLoginTime": "2024-11-29T12:17:01.746827"
    },
    "title": "리액트 공부 자료 올립니다",
    "subject": "유기화학",
    "faculties": [
      "공과대학"
    ],
    "content": "제발 FTP 업로드되게해주세요",
    "documentTypes": [
      "DOCUMENT"
    ],
    "postTier": "CHEONMIN",
    "thumbnailUrl": "http://221.149.185.157/sejong-malsami/thumbnail/THUMBNAIL_리액트_훅_20241129_122242_thumbnail_45209eec-a0fc-4cc3-a0e8-3dc1ad45a94f.jpeg",
    "likeCount": 0,
    "dislikeCount": 0,
    "commentCount": 0,
    "viewCount": 0,
    "isDepartmentPrivate": false,
    "isPopular": false
  },
  "documentPostsPage": null,
  "documentRequestPost": null,
  "documentRequestPostsPage": null,
  "documentBoardLike": null,
  "documentFiles": [
    {
      "createdDate": "2024-11-29T12:22:42.858789",
      "updatedDate": "2024-11-29T12:22:42.858789",
      "isEdited": false,
      "isDeleted": false,
      "isLiked": false,
      "documentFileId": "2fdb3088-b372-4914-a75e-c93ae68618a6",
      "documentPost": {
        "createdDate": "2024-11-29T12:22:31.312952",
        "updatedDate": "2024-11-29T12:23:59.395858",
        "isEdited": true,
        "isDeleted": false,
        "isLiked": false,
        "dailyScore": 0,
        "weeklyScore": 0,
        "documentPostId": "a3b28ed5-50db-4d40-ad70-dd210b3093bd",
        "member": {
          "createdDate": "2024-11-23T12:16:08.491587",
          "updatedDate": "2024-11-29T12:17:02.081397",
          "isEdited": true,
          "isDeleted": false,
          "isLiked": false,
          "memberId": "1acdf07f-e104-465d-b26f-772153f6fc0d",
          "studentId": 18010561,
          "studentName": "서새찬",
          "uuidNickname": "b63d7b",
          "major": "바이오융합공학전공",
          "academicYear": "4",
          "enrollmentStatus": "졸업",
          "profileUrl": null,
          "isNotificationEnabled": true,
          "roles": [
            "ROLE_USER",
            "ROLE_ADMIN"
          ],
          "accountStatus": "ACTIVE",
          "lastLoginTime": "2024-11-29T12:17:01.746827"
        },
        "title": "리액트 공부 자료 올립니다",
        "subject": "유기화학",
        "faculties": [
          "공과대학"
        ],
        "content": "제발 FTP 업로드되게해주세요",
        "documentTypes": [
          "DOCUMENT"
        ],
        "postTier": "CHEONMIN",
        "thumbnailUrl": "http://221.149.185.157/sejong-malsami/thumbnail/THUMBNAIL_리액트_훅_20241129_122242_thumbnail_45209eec-a0fc-4cc3-a0e8-3dc1ad45a94f.jpeg",
        "likeCount": 0,
        "dislikeCount": 0,
        "commentCount": 0,
        "viewCount": 0,
        "isDepartmentPrivate": false,
        "isPopular": false
      },
      "uploader": {
        "createdDate": "2024-11-23T12:16:08.491587",
        "updatedDate": "2024-11-29T12:17:02.081397",
        "isEdited": true,
        "isDeleted": false,
        "isLiked": false,
        "memberId": "1acdf07f-e104-465d-b26f-772153f6fc0d",
        "studentId": 18010561,
        "studentName": "서새찬",
        "uuidNickname": "b63d7b",
        "major": "바이오융합공학전공",
        "academicYear": "4",
        "enrollmentStatus": "졸업",
        "profileUrl": null,
        "isNotificationEnabled": true,
        "roles": [
          "ROLE_USER",
          "ROLE_ADMIN"
        ],
        "accountStatus": "ACTIVE",
        "lastLoginTime": "2024-11-29T12:17:01.746827"
      },
      "thumbnailUrl": "http://221.149.185.157/sejong-malsami/thumbnail/THUMBNAIL_리액트_훅_20241129_122242_thumbnail_45209eec-a0fc-4cc3-a0e8-3dc1ad45a94f.jpeg",
      "filePath": "/projects/sejong-malsami/document/DOCUMENT_리액트_훅_cbef543b-e9e7-4487-8318-cac81e01f02e.pdf",
      "originalFileName": "리액트 훅 .pdf",
      "uploadedFileName": "DOCUMENT_리액트_훅_cbef543b-e9e7-4487-8318-cac81e01f02e.pdf",
      "fileSize": 4555318,
      "mimeType": "PDF",
      "downloadCount": 0,
      "password": null,
      "isInitialPasswordSet": false
    },
    {
      "createdDate": "2024-11-29T12:23:59.39174",
      "updatedDate": "2024-11-29T12:23:59.39174",
      "isEdited": false,
      "isDeleted": false,
      "isLiked": false,
      "documentFileId": "08e59a8e-33b4-4816-89a3-7a1b7cef47cf",
      "documentPost": {
        "createdDate": "2024-11-29T12:22:31.312952",
        "updatedDate": "2024-11-29T12:23:59.395858",
        "isEdited": true,
        "isDeleted": false,
        "isLiked": false,
        "dailyScore": 0,
        "weeklyScore": 0,
        "documentPostId": "a3b28ed5-50db-4d40-ad70-dd210b3093bd",
        "member": {
          "createdDate": "2024-11-23T12:16:08.491587",
          "updatedDate": "2024-11-29T12:17:02.081397",
          "isEdited": true,
          "isDeleted": false,
          "isLiked": false,
          "memberId": "1acdf07f-e104-465d-b26f-772153f6fc0d",
          "studentId": 18010561,
          "studentName": "서새찬",
          "uuidNickname": "b63d7b",
          "major": "바이오융합공학전공",
          "academicYear": "4",
          "enrollmentStatus": "졸업",
          "profileUrl": null,
          "isNotificationEnabled": true,
          "roles": [
            "ROLE_USER",
            "ROLE_ADMIN"
          ],
          "accountStatus": "ACTIVE",
          "lastLoginTime": "2024-11-29T12:17:01.746827"
        },
        "title": "리액트 공부 자료 올립니다",
        "subject": "유기화학",
        "faculties": [
          "공과대학"
        ],
        "content": "제발 FTP 업로드되게해주세요",
        "documentTypes": [
          "DOCUMENT"
        ],
        "postTier": "CHEONMIN",
        "thumbnailUrl": "http://221.149.185.157/sejong-malsami/thumbnail/THUMBNAIL_리액트_훅_20241129_122242_thumbnail_45209eec-a0fc-4cc3-a0e8-3dc1ad45a94f.jpeg",
        "likeCount": 0,
        "dislikeCount": 0,
        "commentCount": 0,
        "viewCount": 0,
        "isDepartmentPrivate": false,
        "isPopular": false
      },
      "uploader": {
        "createdDate": "2024-11-23T12:16:08.491587",
        "updatedDate": "2024-11-29T12:17:02.081397",
        "isEdited": true,
        "isDeleted": false,
        "isLiked": false,
        "memberId": "1acdf07f-e104-465d-b26f-772153f6fc0d",
        "studentId": 18010561,
        "studentName": "서새찬",
        "uuidNickname": "b63d7b",
        "major": "바이오융합공학전공",
        "academicYear": "4",
        "enrollmentStatus": "졸업",
        "profileUrl": null,
        "isNotificationEnabled": true,
        "roles": [
          "ROLE_USER",
          "ROLE_ADMIN"
        ],
        "accountStatus": "ACTIVE",
        "lastLoginTime": "2024-11-29T12:17:01.746827"
      },
      "thumbnailUrl": "http://221.149.185.157/sejong-malsami/thumbnail/THUMBNAIL_리액트_훅_20241129_122359_thumbnail_3024f4a4-b158-43f7-8815-cc48242594a5.jpeg",
      "filePath": "/projects/sejong-malsami/document/DOCUMENT_리액트_훅_72dfe226-88e4-49e2-90fa-7ee8fb0fc6e6.pptx",
      "originalFileName": "리액트 훅 .pptx",
      "uploadedFileName": "DOCUMENT_리액트_훅_72dfe226-88e4-49e2-90fa-7ee8fb0fc6e6.pptx",
      "fileSize": 22112707,
      "mimeType": "PPTX",
      "downloadCount": 0,
      "password": null,
      "isInitialPasswordSet": false
    }
  ]
}
```

**Comment by Cassiiopeia** [comment]
확인후 이슈 패쇄 부탁드립니다

**Comment by newjinlee** [comment]
확인했습니다!
