### ISSUE TITLE
🔥 ❗ [긴급][버그][랜딩] 주간 일기 질문 게시글 반환 오류

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-BE#647]
🗒️ 설명
---
- 랜딩 페이지에서
- https://api.sejong-malsami.co.kr/api/landing/popular/question/daily
- 호출시 500 에러 발생

페이로드
pageSize: 10

응답
Page size must not be less than one

이게도대체 뭘까요.... 페이지 사이즈가 10개인데
왜 1보다 작은 페이지 사이즈가 들어간다는거지.
흠... 서버 문제같습니다

왜 여기만 발생하죠?
Redis 를 사용하는것으로 캐시로직을 바꾸어서 그런지

아니면 내부로직이 잘못되어있는지 확인이 필요해 보입니다

백지훈님이 부재중이셔서 제가 먼저 작업해보도록 하겠습니다

아래 로그내역에서 볼수있는것처럼 pageNumber=0, pageSize=5 왜 페이지 사이즈를 10으로 보냈는데 5개라고 파라미터가 들어갔는지 확인부터 해봐야겠네요...

```
2024-12-17 01-07-43.247 [http-nio-8080-exec-1] DEBUG org.springframework.web.servlet.DispatcherServlet - POST "/api/landing/popular/document/daily", parameters={multipart}
2024-12-17 01-07-43.247 [http-nio-8080-exec-10]  INFO com.balsamic.sejongmalsami.util.log.MethodInvocationLoggingAspect - [getDailyPopularQuestionPost] RequestID: null, Result: INTERNAL_SERVER_ERROR
2024-12-17 01-07-43.249 [http-nio-8080-exec-1]  INFO com.balsamic.sejongmalsami.util.log.MethodInvocationLoggingAspect - [getDailyPopularDocumentPost] RequestID: null, Parameter: []
2024-12-17 01-07-43.249 [http-nio-8080-exec-10] ERROR com.balsamic.sejongmalsami.util.exception.GlobalExceptionHandler - Page size must not be less than one
java.lang.IllegalArgumentException: Page size must not be less than one
2024-12-17 01-07-43.250 [http-nio-8080-exec-9]  INFO com.balsamic.sejongmalsami.util.log.MethodInvocationLoggingAspect - [getFilteredQuestionPosts] RequestID: null, Parameter: [QuestionCommand(postId=null, memberId=null, title=null, questionPostId=null, content=null, subject=null, attachmentFiles=null, questionPresetTags=null, customTags=null, rewardYeopjeon=null, contentType=null, isPrivate=null, pageNumber=0, pageSize=5, faculty=null, sortType=null, chaetaekStatus=null)]
```

![image](https://github.com/user-attachments/assets/2be80902-79a6-4d1e-922d-77e5048cab31)

서버 에러코드는 다음과 같습니다

![image](https://github.com/user-attachments/assets/597fae2c-f145-41a0-a098-3b0ea7f49bb3)

```
2024-12-17 01-07-43.246 [http-nio-8080-exec-10]  INFO com.balsamic.sejongmalsami.util.log.ExecutionTimeLoggingAspect - [getDailyPopularQuestionPost] 실행시간: 15ms
2024-12-17 01-07-43.247 [http-nio-8080-exec-1] DEBUG org.springframework.web.servlet.DispatcherServlet - POST "/api/landing/popular/document/daily", parameters={multipart}
2024-12-17 01-07-43.247 [http-nio-8080-exec-10]  INFO com.balsamic.sejongmalsami.util.log.MethodInvocationLoggingAspect - [getDailyPopularQuestionPost] RequestID: null, Result: INTERNAL_SERVER_ERROR
2024-12-17 01-07-43.249 [http-nio-8080-exec-1]  INFO com.balsamic.sejongmalsami.util.log.MethodInvocationLoggingAspect - [getDailyPopularDocumentPost] RequestID: null, Parameter: []
2024-12-17 01-07-43.249 [http-nio-8080-exec-10] ERROR com.balsamic.sejongmalsami.util.exception.GlobalExceptionHandler - Page size must not be less than one
java.lang.IllegalArgumentException: Page size must not be less than one
2024-12-17 01-07-43.250 [http-nio-8080-exec-9]  INFO com.balsamic.sejongmalsami.util.log.MethodInvocationLoggingAspect - [getFilteredQuestionPosts] RequestID: null, Parameter: [QuestionCommand(postId=null, memberId=null, title=null, questionPostId=null, content=null, subject=null, attachmentFiles=null, questionPresetTags=null, customTags=null, rewardYeopjeon=null, contentType=null, isPrivate=null, pageNumber=0, pageSize=5, faculty=null, sortType=null, chaetaekStatus=null)]
        at org.springframework.data.domain.AbstractPageRequest.<init>(AbstractPageRequest.java:50)
        at org.springframework.data.domain.PageRequest.<init>(PageRequest.java:46)
        at org.springframework.data.domain.PageRequest.of(PageRequest.java:73)
        at org.springframework.data.domain.PageRequest.of(PageRequest.java:61)
        at com.balsamic.sejongmalsami.service.PopularPostService.getPagedPosts(PopularPostService.java:317)
        at com.balsamic.sejongmalsami.service.PopularPostService.getDailyPopularQuestionPosts(PopularPostService.java:63)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:379)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
        at com.balsamic.sejongmalsami.service.PopularPostService$$SpringCGLIB$$0.getDailyPopularQuestionPosts(<generated>)
        at com.balsamic.sejongmalsami.controller.LandingController.getDailyPopularQuestionPost(LandingController.java:63)
        at jdk.internal.reflect.GeneratedMethodAccessor309.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at com.balsamic.sejongmalsami.util.log.ExecutionTimeLoggingAspect.logMethod(ExecutionTimeLoggingAspect.java:24)
        at jdk.internal.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:173)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at com.balsamic.sejongmalsami.util.log.MethodInvocationLoggingAspect.logMethod(MethodInvocationLoggingAspect.java:39)
        at jdk.internal.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
2024-12-17 01-07-43.251 [http-nio-8080-exec-9]  INFO com.balsamic.sejongmalsami.service.QuestionPostService - chaetaekStatus가 null이므로 기본값인 ALL로 설정합니다.
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:173)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
        at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
        at org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:479)
        at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:340)
        at org.springframework.security.web.ObservationFilterChainDecorator.lambda$wrapSecured$0(ObservationFilterChainDecorator.java:82)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:128)
        at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at com.balsamic.sejongmalsami.util.filter.TokenAuthenticationFilter.doFilterInternal(TokenAuthenticationFilter.java:43)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$0(ObservationFilterChainDecorator.java:323)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:224)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
        at org.springframework.web.servlet.handler.HandlerMappingIntrospector.lambda$createCacheFilter$3(HandlerMappingIntrospector.java:195)
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
        at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
        at org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration$CompositeFilterChainProxy.doFilter(WebMvcSecurityConfiguration.java:230)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:113)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:904)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
        at java.base/java.lang.Thread.run(Thread.java:833)
       
```

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia  @Chuseok22 
- 프론트엔드: @newjinlee 
- 디자인: 이름

**Comment by Chuseok22** [comment]
확인했습니다

**Comment by Chuseok22** [comment]
현재 인기글 로직은 파라미터를 받지 않습니다
작동 로직은 다음과 같습니다
1. 스프링 스케줄러에 등록된 일정 시간마다 인기 점수를 업데이트 하고 redis에 상위 30개의 글 id를 저장합니다.
2. 사용자로부터 요청이 들어오면 저장된 30개의 인기글을 반환합니다.

```
  @Override
  @PostMapping(value = "/popular/question/daily")
  @LogMonitoringInvocation
  public ResponseEntity<QuestionDto> getDailyPopularQuestionPost() {
    return ResponseEntity.ok(popularPostService.getDailyPopularQuestionPosts());
  }

  @Override
  @PostMapping(value = "/popular/question/weekly")
  @LogMonitoringInvocation
  public ResponseEntity<QuestionDto> getWeeklyPopularQuestionPost() {
    return ResponseEntity.ok(popularPostService.getWeeklyPopularQuestionPosts());
  }

  @Override
  @PostMapping(value = "/popular/document/daily")
  @LogMonitoringInvocation
  public ResponseEntity<DocumentDto> getDailyPopularDocumentPost() {
    return ResponseEntity.ok(popularPostService.getDailyPopularDocumentPosts());
  }

  @Override
  @PostMapping(value = "/popular/document/weekly")
  @LogMonitoringInvocation
  public ResponseEntity<DocumentDto> getWeeklyPopularDocumentPost() {
    return ResponseEntity.ok(popularPostService.getWeeklyPopularDocumentPosts());
  }
```

해당 문제는 redis에 저장된 인기글이 없는 경우 (question/daily 같은 경우 요청 시점으로부터 24시간 이내에 등록 된 글만 반환하도록 로직이 작성되어있음) 오류가 발생합니다.
따라서 방어 로직을 추가하여 수정하도록 하겠습니다

**Comment by Chuseok22** [comment]
#653 

<redis에 저장된 인기글이 없는 경우>
* 저장된 인기글이 없는 경우 에러코드를 반환하도록 수정했습니다.

```
2024-12-24 11-02-13.737 [http-nio-8080-exec-2] ERROR com.balsamic.sejongmalsami.util.exception.GlobalExceptionHandler - 저장된 인기글이 없습니다.
com.balsamic.sejongmalsami.util.exception.CustomException: 저장된 인기글이 없습니다.
        at com.balsamic.sejongmalsami.service.PopularPostService.getIdsFromRedis(PopularPostService.java:287)
2024-12-24 11-02-13.742 [http-nio-8080-exec-2] DEBUG org.springframework.web.servlet.DispatcherServlet - Completed 400 BAD_REQUEST
        at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$0(ObservationFilterChainDecorator.java:323)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:224)
```

<redis에 저장된 인기글이 30개보다 적은경우>
* question/daily에 인기글 1개만 저장 된 상태로 요청 보냈습니다
* redis에 해당 글 id도 잘 저장되고, 반환도 제대로 되는 것 확인했습니다.

![스크린샷 2024-12-24 오전 11 12 53](https://github.com/user-attachments/assets/03b33f06-31f8-45d7-8467-6b4bf838b767)

![스크린샷 2024-12-24 오전 11 11 50](https://github.com/user-attachments/assets/61f10f31-1236-44b2-b444-d37969444b8f)

**Comment by newjinlee** [comment]
reopen 하겠습니다 ~

**Comment by Chuseok22** [comment]
@newjinlee 
* 인기글이 없는 경우 빈 Page객체를 반환하도록 설정했습니다
확인 후 이슈 닫아주세용~

![스크린샷 2024-12-26 오전 8 59 16](https://github.com/user-attachments/assets/f10e3902-fed3-43ef-b756-6ed271709e07)
![스크린샷 2024-12-26 오전 8 59 22](https://github.com/user-attachments/assets/2d60545c-db3e-4413-ba08-abc80f62bd28)

**Comment by Cassiiopeia** [comment]
확인되어 이슈닫습니다
